config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts

  resources :locations, only: [:show]
  resources :locations, path: "/admin/locations"
  get "locations/:id/pikeup", to: "locations#pikeup", as: "pikeup"

  resources :dragons

  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :dragons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dragon.rb
class Dragon < ApplicationRecord
  validates :name, uniqueness: true

  belongs_to :account, optional: true
  belongs_to :location, optional: true

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :dragons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dragons_controller.rb
class DragonsController < ApplicationController

  def index
    @dragons = current_account.dragons
  end

  private


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end
  def create
    @location = Location.new
    if @location.save
      redirect_to root_path, notice: "new location!"
    else
      render :new
    end
  end
  def show
    @locations = Location.order(:name)
    @location = Location.find(params[:id])
    @eggs = Dragon.where("location_id = ? AND account_id = ?", params[:id], 0)
    # testing: coast eggs
    if @eggs.size < 3 and
      des = dragon_description
      nam = generate_name
      Dragon.create(account_id: 0, location_id: params[:id], name: nam, description: des)
    end
    p "#{@eggs.size}"
  end

  def pikeup
    @id = params[:id]
    Dragon.find(params[:id]).update(account_id: current_account.id)
  end

  private
  def dragon_description

    coast = [
        "This egg has an orange aura radiating from it.",
        "This egg is tiny and made out of several pieces of paper folded together.",
        "This light egg is floating in the air.",
        "This egg has a faint green glow around it.",
        "It's bright. And pink.",
        "This egg is soft and smells uncannily like cheese.",
        "This egg reminds you of the sea."
    ]

    if @location.name == 'Coast'
      return coast.sample
    else
      return nil
    end

  end
  def generate_name
    a = ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "a", "s", "d", "f", "g", "h", "j", "k", "l", "z", "x", "c", "v", "b", "n", "m", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Z", "X", "C", "V", "B", "N", "M"]
    return a.shuffle.sample(5).join
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
    @locations = Location.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dragons/index.html.erb
<div class="container">

  <div class="row">
    <div class="col">
      Share
    </div>
    <div class="col">
      Badge
    </div>
    <div class="col">
      State
    </div>
  </div>


  <div class="row pt-5">
    <div class="col">Name</div>
    <div class="col">Description</div>
  </div>
  <% @dragons.each do |dragon| %>
    <div class="row">
      <div class="col"><%= dragon.name %></div>
      <div class="col"><%= dragon.description %></div>
    </div>
  <% end %>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      footer<br>
      email: test@dev.com<br>
      password: testdev
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">

    <div class="col">
      <%= link_to "Dragon Cave Clone", root_path, class: "h3" %>
    </div>

    <div class="col">
      <div class="float-right">
        <div class="row ">
          <% if account_signed_in? %>
            <%= link_to "Sign out", destroy_account_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log in", new_account_session_path, class: "pr-2" %>
            <%= link_to "Sign up", new_account_registration_path %>
          <% end %>
        </div>
        <div class="row pt-2">
          <%= link_to "Cave", root_path, class: "pr-2" %>
          <% if account_signed_in? %>
            <%= link_to "Account", edit_account_registration_path, class: "pr-2" %>
            <%= link_to "Dragons", dragons_path, class: "pr-2" %>
            <%= link_to "Trading", "#", class: "pr-2" %>
          <% end %>
          <%= link_to "Help", "#", class: "pr-2" %>
          <%= link_to "Forum", "#" %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dragon Cave Clone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <div class="row justify-content-center">

        <% if account_signed_in? && current_account.id == 100 %>
          <div class="col-sm-2">
            <%= render partial: "layouts/admin" %>
          </div>
        <% end %>

        <div class="col-sm-8">
          <%= render partial: "layouts/header" %>
          <%= yield %>
          <%= render partial: "layouts/footer" %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/locations/index.html.erb
all locations

app/views/locations/new.html.erb
new location
<%= form_for(@location) do |f| %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <%= f.submit "Create", class: "btn btn-primary" %>

<% end %>

app/views/locations/pikeup.html.erb
<div class="contains">
  <div class="row">
    <div class="col">
      success pikeup
      <%= @id %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="contains">
  <p class="h3 pt-5"><%= @location.name %></p>

  <div class="row">
    <% @locations.each do |location| %>
      <div class="col">
          <%= link_to location.name, location_path(location) %>
      </div>
    <% end %>
  </div>

  <div class="row pt-2">
    <p><%= @location.description %></p>
    <p>You don’t want to disturb the dragons, but some of the eggs are far enough away that you could steal one.
      Three of the eggs catch your eye. Which do you take?</p>
      
    <% @eggs.each do |egg| %>
    <div class="col text-center">
      <%= link_to '<img src="/egg.gif" alt="egg">'.html_safe, pikeup_path(egg) %><br>
      <%= egg.description %>
    </div>
    <% end %>

  </div>

</div>